cd /root
cp xp.sh /usr/bin/xp
cp vmessmenu.sh /usr/bin/vmessmenu
cp vlessmenu.sh /usr/bin/vlessmenu
cp user.sh /usr/bin/user
cp trojanmenu.sh /usr/bin/trojanmenu
cp renew-vmess.sh /usr/bin/renew-vmess
cp renew-vless.sh /usr/bin/renew-vless
cp renew-trojan-grpc.sh /usr/bin/renew-trojan-grpc
cp renew-trojan.sh /usr/bin/renew-trojan
cp menu.sh /usr/bin/menu
cp help.sh /usr/bin/help
cp grpcmenu.sh /usr/bin/grpcmenu
cp del-vmess.sh /usr/bin/del-vmess
cp del-vless.sh /usr/bin/del-vless
cp del-trojan-grpc.sh /usr/bin/del-trojan-grpc
cp del-trojan.sh /usr/bin/del-trojan
cp clear-log.sh /usr/bin/clear-log
cp cert.sh /usr/bin/cert
cp cek-vmess.sh /usr/bin/cek-vmess
cp cek-service.sh /usr/bin/cek-service
cp cek-vless.sh /usr/bin/cek-vless
cp cek-trojan-grpc.sh /usr/bin/cek-trojan-grpc
cp cek-trojan.sh /usr/bin/cek-trojan
cp add-vmess.sh /usr/bin/add-vmess
cp add-vless.sh /usr/bin/add-vless
cp add-trojan-grpc.sh /usr/bin/add-trojan-grpc
cp add-trojan.sh /usr/bin/add-trojan
cd /usr/bin
chmod +x xp
chmod +x vmessmenu
chmod +x vlessmenu
chmod +x user
chmod +x trojanmenu
chmod +x renew-vmess
chmod +x renew-vless
chmod +x renew-trojan-grpc
chmod +x renew-trojan
chmod +x menu
chmod +x help
chmod +x grpcmenu
chmod +x del-vmess
chmod +x del-vless
chmod +x del-trojan-grpc
chmod +x del-trojan
chmod +x clear-log
chmod +x cert
chmod +x cek-vmess
chmod +x cek-vless
chmod +x cek-trojan-grpc
chmod +x cek-trojan
chmod +x cek-service
chmod +x add-vmess
chmod +x add-vless
chmod +x add-trojan-grpc
chmod +x add-trojan
cd
echo "Sukses ngab"

